---
- name: Scan network using ICMP ping to get machine names
  hosts: all
  gather_facts: no
  connection: local  # Utilise la connexion locale pour éviter SSH
  tasks:
    - name: Check if the machine responds to ICMP ping
      ansible.builtin.command:
        cmd: ping -c 1 -W 1 {{ inventory_hostname }}
      register: ping_result
      ignore_errors: yes

    - name: Gather hostname if the machine is reachable
      ansible.builtin.command:
        cmd: "nslookup {{ inventory_hostname }} | grep 'name ='"
      when: ping_result.rc == 0
      register: host_info
      ignore_errors: yes

    - name: Display hostname
      debug:
        msg: "IP: {{ inventory_hostname }} - Hostname: {{ host_info.stdout }}"
      when: host_info is defined
