---
- name: Scan network using ICMP ping to get machine names
  hosts: all
  gather_facts: no
  tasks:
    - name: Check if the machine responds to ICMP ping
      ansible.builtin.command: ping -c 1 -W 1 {{ inventory_hostname }}
      register: ping_result
      ignore_errors: yes

    - name: Gather hostname if the machine is reachable
      ansible.builtin.setup:
        filter: ansible_hostname
      when: ping_result.rc == 0
      register: host_info

    - name: Display hostname
      debug:
        msg: "IP: {{ inventory_hostname }} - Hostname: {{ host_info.ansible_facts.ansible_hostname }}"
      when: host_info is defined
